#= require jquery
#= require jquery_ujs
#= require turbolinks
#= require nprogress
#= require nprogress-turbolinks
#= require bootstrap
#= require base
#= require_tree ./lib
#= require hogan.js
#= require bootstrap3-typeahead/bootstrap3-typeahead
#= require typeahead.js/dist/bloodhound
#= require_self